import Head from "next/head"
import { Analytics } from '@vercel/analytics/next';

export const metadata = {
  title: 'Andrews Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>Andrews Portfolio</title>
        <meta name="description" content="This is the home page description." />
        <link rel="icon" type="image/png" href="/favicon.ico"/>
      </Head>
      <body suppressHydrationWarning>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
